.TH LIBTRITH 3 "December 2010" "Trith" "Trith Manual"
.SH NAME
\fBlibtrith\fP \-\- the Trith embeddable runtime library
.SH LIBRARY
Trith (libtrith, \-ltrith)
.SH SYNOPSIS
.B #include <trith.h>
.SH DESCRIPTION
TODO
.SH ERRORS
TODO
.SH NOTES
TODO
.SH BUGS
TODO
.SH EXAMPLES
TODO
.SH SEE ALSO
.BR trith (7)
