.TH TRITH 7 "December 2010" "Trith.org" "Trith Manual"
.SH NAME
\fBtrith\fP \-\- an experimental concatenative programming language
.SH SYNOPSIS
\fB3th\fP [\fB\-\-version\fR] [\fB\-\-help\fR] \fIcommand\fR [\fIargs\fR...]
.br
\fB3cc\fP [options] [\fIfile\fR...]
.br
\fB3sh\fP [options] [\fIfile\fR...]
.br
\fB3vm\fP [options] [\fIfile\fR...]
.SH DESCRIPTION
TODO
.SH OPERATORS
TODO
.SS Core Operators
TODO
.SS Sequence Operators
TODO
.SS Math Operators
TODO
.SH ENVIRONMENT
TODO
.SH FILES
TODO
.SH NOTES
TODO
.SH BUGS
Please report bugs to the mailing list at \fB<trith@googlegroups.com>\fP
.SH AUTHOR
Arto Bendiken <arto@bendiken.net>
.SH SEE ALSO
.BR 3th (1),
.BR 3sh (1),
.BR 3vm (1),
.BR 3cc (1),
.BR libtrith (3)
