.TH 3CC 1 "December 2010" "Trith" "Trith Manual"
.SH NAME
\fB3cc\fP \-\- the Trith compiler
.SH SYNOPSIS
\fB3cc\fP [options] [\fIfile\fR...]
.SH DESCRIPTION
TODO
.SH OPTIONS
TODO
.SH EXIT STATUS
The \fB3cc\fP program exits with 0 on success, and with >0 if an error
occurs.
.SH ENVIRONMENT
TODO
.SH FILES
TODO
.SH NOTES
TODO
.SH BUGS
TODO
.SH EXAMPLES
TODO
.SH SEE ALSO
.BR 3th (1),
.BR 3sh (1),
.BR 3vm (1),
.BR trith (7)
